# 第5回　テキスト分析の基礎

文字列の使い方は第2回講義でやっているのでそれを参照、ここでは課題の取り組みについて記載するに留める

### Q1

n次元ベクトル空間における、任意の2つのベクトル  

$\mathbf{x} = (x_1, x_2, \ldots, x_n)$, $\mathbf{y} = (y_1, y_2, \ldots, y_n)$ の間のcos類似度 $\cos(X, Y)$は以下のように定義されます。

$$
\cos(X, Y) = \frac{\mathbf{x} \cdot \mathbf{y}}{\|\mathbf{x}\|_2 \|\mathbf{y}\|_2}
= \frac{\sum_{i=1}^{n} x_i y_i}{\sqrt{\sum_{i=1}^{n} x_i^2} \sqrt{\sum_{i=1}^{n} y_i^2}}
$$

入力ベクトル $\mathbf{x}, \mathbf{y}$ をそれぞれ NumPy の配列として引数で受け取り、  
それらのベクトル間のcos類似度を計算して返す関数 `cos_sim` を完成させてください。

In [11]:
import numpy as np

In [12]:
def cos_sim(vec1, vec2):
  # linalg.norm()で
  calc =  np.dot(vec1,vec2) / np.linalg.norm(vec1) * np.linalg.norm(vec2)
  return calc

x = [1,2,3,4,5]
y = [2,4,6,8,10]

print(cos_sim(x,y))

220.0


### Q2
"course_list.csv" ファイルには以下のように各行に講義名のテキストデータが含まれています。以下では、このファイルを読み込み、各講義のベクトルを作成し、講義間の類似度を求めるコードを実装します。

``` 
## course_list.csvファイル
行動神経科学
認知心理学
性格心理学
スポーツ栄養学
グローバル教養特別演習Ⅰ(13)
認知行動障害論
スポーツバイオメカニクス
...
``` 

まず必要なモジュールをimportします。

In [13]:
import json
import csv
import numpy as np
import pandas as pd

In [14]:
import os

# カレントディレクトリを取得
cwd = os.getcwd()
print(cwd)

/Users/namaisawashogo/my-project/premaster/data_mining/code


### Q2.1
`course_list.csv`ファイルを1行ずつ順番に読み込み、その各行を要素とするリストを作成して返す course list 関数を完成さてください。作成されたリストは変数 courses で受け取ります。以降の処理では、リスト courses のインデックスをその要素(講義名)のIDとして扱います。

In [15]:
def course_list ():
  courses = []
  with open("../data/course_list.csv") as f:
    reader = csv.reader(f)

    for row in reader:
      courses.append(row[0])
  return courses

In [16]:
courses = course_list()
print(courses[1:6])

['特別講義\u3000国際紛争研究（外国語科目）', "特別講義\u3000Japan in Today's World（外国語科目）", '生態統計学', '商法演習', 'ロシア・旧ソ連法']


### Q2.2
"keywor_list.csv" ファイルを1行ずつ順番に読み込み、その各行を要素とするリストを作成して返す vocab list 関数を完成さてください。作成されたリストは変数 vocab で受け取ります。以降の処理では、リスト vocab のインデックスをその要素(単語)のIDとして扱います。リスト vocab は以降の処理における語彙となります。

In [17]:
def vocab_list():
  keyword = []
  with open('../data/keyword_list.csv') as f:
    reader = csv.reader(f)

    for row in reader:
      keyword.append(row[0])
  return keyword


In [18]:
vocab = vocab_list()
print(vocab[1:6])

['演習', '特殊', '講義', '科学', '研究']


### Q2.3
リスト courses と vocab を引数で受け取り、単語のID(リスト vocab のその単語のインデックス)をキー、その単語のDF (Document Frequency)を値とする辞書を作成して返す count_df 関数を作成してください。作成された辞書は変数 df で受け取ります。この場合、ある単語のDF値はその単語を講義名に含む講義数に対応します。

In [19]:
def count_df(courses, vocab):
    df ={}

    for i, word in enumerate(vocab):
        count=0
        for course in courses:
            if word in course: # 講義名に対象のwordが含まれているか
                count += 1
        df[i] = count
    return df

In [20]:
count = count_df(courses, vocab)
print(list(count.items())[:5])

[(0, 0), (1, 821), (2, 503), (3, 460), (4, 407)]


In [21]:
for i, v in list(count.items())[:5]:
  print(vocab[i], v)


keyword 0
演習 821
特殊 503
講義 460
科学 407


### Q2.4.1
リスト vocab の各単語を次元とする講義ベクトルを考えます。講義ベクトルの長さはリスト vocab の長さと等しく、リスト vocab のインデックス i の単語 vocab[i]が講義名に含まれる時、講義ベクトルの i 番目の要素は 1、含まれなければ0とします。
以下では、リスト courses と vocab を引数で受け取り、リスト courses の各講義のベクトルを行、リスト vocab の各単語を列とした NumPy の行列を作成して返すlec word matrix 関数を完成させてください。作成した講義-単語行列は、講義(行) の講義名に単語(列)が含まれていれば、その要素が1であるような行列です。

In [22]:
def lec_word_matrix(_courses, _vocab):
    # （講義数, 単語数）の行列を0で初期化
    lec_word = np.zeros((len(_courses), len(_vocab)))

    # 各講義・各単語についてチェック
    for i in range(len(_courses)):
        for j in range(len(_vocab)):
            if _vocab[j] in _courses[i]:
                lec_word[i][j] = 1

    return lec_word

In [23]:
print(np.shape(lec_word_matrix(courses, vocab)))
print(lec_word_matrix(courses, vocab)[:10,:10])

(4629, 979)
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [24]:
# 正解なら17731
np.sum(lec_word_matrix(courses, vocab))

np.float64(17731.0)

In [25]:
assert 17731 == np.sum(lec_word_matrix(courses, vocab))

### Q2.4.2
Q2.4.1で作成した講義-単語行列の各要素を、その講義の講義名に単語が含まれるか否かの 1or0ではなく、その講義の講義名に単語が何回含まれるか(TF: Term Frequency)で表した行列を作成して返す `lec_word_tf_matrix()` 関数を完成させてください。

In [26]:
def lec_word_tf_matrix(_courses, _vocab):
    ###(講義数,単語数)の行列を初期化するコード(ヒント np.zeros()) ###
    lec_tf = np.zeros((len(_courses), len(_vocab)))

    ### lec_word[i,j]="講義名courses[i]に単語vocab[j]が含まれる数”、とする処理のコード ###
    # 各講義・各単語についてチェック
    for i in range(len(_courses)):
        for j in range(len(_vocab)):
            if _vocab[j] in _courses[i]:
                lec_tf[i][j] = _courses[i].count(_vocab[j])

    return lec_tf

In [27]:
# 正解なら18045
np.sum(lec_word_tf_matrix(courses, vocab))

np.float64(18045.0)

In [28]:
# 講義「情報社会及び情報倫理」は「情報」が2回出るので行列要素が2
lec_word_tf_matrix(courses, vocab)[courses.index('情報社会及び情報倫理'), vocab.index('情報')]

np.float64(2.0)

### Q2.4.3
Q2.4.2で作成した講義-単語行列の各要素(講義$i$の単語$j$の$TF_{ij}$)にその単語のIDF値を掛けたTFIDF値を要素とする行列を作成して返す `lec_word_tfidf_matrix()` 関数を完成させてください。

作成した行列は変数 `tfidf_matrix` で受け取ります。

$$\text{TFIDF}_{ij} = \text{TF}_{ij} \times \log\left(\frac{N}{\text{DF}_j}\right)$$
です。

- $\text{TF}_{ij}$: Q2.4.2 の値（講義 $i$ に単語 $j$ が何回出るか）
- $\text{DF}_j$: 単語 $j$ を含む講義数（Q2.3）
- $N$: 講義総数（`len(courses)`）

ここで、講義i、単語jのTFIDF値はコードで以下のように定義

```python 
TFIDF=TF_ij*log(すべての講義数/単語」のDF)=TF_ij*log(len(courses)/d f[j])

``` 

log の計算には np.log()を使用してよいです。

In [35]:
def lec_word_tfidf_matrix(_courses, _vocab, _df):
    
    lec_word = np.zeros((len(_courses), len(_vocab)))
    N = len(_courses) # 全講義数

    # 各講義・各単語についてループ
    for i in range(len(_courses)):
        for j in range(len(_vocab)):
            # TF: 講義 i の中に 単語 j が何回出現するか
            tf = _courses[i].count(_vocab[j])

            # DF: 単語 j を含む講義数（Q2.3 で求めた値）
            df_val = _df[j]

            # DFが0（どの講義にも出てこない単語）の場合は、TFも必ず0なのでTFIDFは0とする
            if df_val == 0 or tf == 0:
                lec_word[i][j] = 0
            else:
                # TFIDF = TF_ij * log(N / DF_j)
                lec_word[i][j] = tf * np.log(N / df_val)

    return lec_word


In [36]:
tfidf_matrix = lec_word_tfidf_matrix(courses, vocab, count)
np.sum(tfidf_matrix)

np.float64(78881.188827943)

In [38]:
# 講義「情報社会及び情報倫理」には「情報」が2回含まれ、「情報」のDF値は155なので対応する行列の要素の値は2* log(4628/155) = 6.79 
tfidf_matrix[courses.index('情報社会及び情報倫理'), vocab.index('情報')]

np.float64(6.793342048224048)

### Q2.5
Q2.4.3で作成した講義-単語行列を元に、入力の講義に対してcos類似度に基づいて他のすべての講義との類似度を計算し、類似する講義名をキー、その類似度を値とした辞書を返す以下の `find_similar_course()` 関数を完成させてください。その際、入力の講義および類似度が0の講義は辞書に含めないようにしてください。cos類似度の計算にはQ1で作成した関数を使ってもよいです。