# 第４回 numpyとmatplotlib
numpyとmatplotlibの話になるよ～少し長いかも

## 4-1. numpy
- 効率的に多次元の配列を扱うことができる。
- 高速な行列演算が可能になるため、行列演算を行う科学技術計算などでよく活用される

In [1]:
import numpy as np

### 4-1-1 配列作成

In [2]:
# array () 関数で配列作成
list_to_array = np.array([1,2,3,4,5])
list_to_array

array([1, 2, 3, 4, 5])

In [3]:
# ndarrayオブジェクトとなる
tuple_to_array = np.array((1,2,3,4,5))
type(tuple_to_array)

numpy.ndarray

In [4]:
# print()で要素が空白区切り
print(list_to_array)
print(tuple_to_array)

[1 2 3 4 5]
[1 2 3 4 5]


### array()
- 第二引数で要素の型を指定できる。ただ混同はできない
- `.dtype()`で型を確認できる
- 一回指定した型も上書きできる

In [5]:
list_to_array = np.array([1,2,3,4,5], dtype = float)
list_to_array.dtype

dtype('float64')

### 4-1-2 多次元配列の作成
配列の中の配列

In [6]:
mul_array = np.array([[1,2,3], [4,5,6]])
print(mul_array)

# 行数と列数
print(mul_array.shape)

# 次元数
print(mul_array.ndim)

# 要素数
print(mul_array.size)

[[1 2 3]
 [4 5 6]]
(2, 3)
2
6


In [7]:
# reshape()で1次元配列を2次元配列に
a = [1,2,3,4,5,6]
a1 = np.array(a)
a2 = a1.reshape(2,3)

print(a1)
print(a2)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [8]:
# 1行1列の要素に代入(1,1)の値を1から0に変更
a2[0,0] = 0

print(a1)
print(a2)

# 多次元配列を1次元配列に戻すravel()
print(a2.ravel())

[0 2 3 4 5 6]
[[0 2 3]
 [4 5 6]]
[0 2 3 4 5 6]


### 練習
以下のリストから1次元リストを作成し、その後３＊３の多次元配列を作成してください。shapeで属性確認をしてください

In [9]:
mylist = [1,2,3,4,5,6,7,8,9]

m1 = np.array(mylist)
m = m1.reshape(3,3)
print(m)

print(m.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


### 4-1-3 様々な配列の作り方

#### `zeros()`関数
全要素が0の配列作成

In [10]:
zero_array1 = np.zeros(5, dtype=int)

# 5要素すべてが0の1次元配列
print(zero_array1)

# 3*3がすべて0の多次元配列
zero_array2 = np.zeros((3,3), dtype=int)
print(zero_array2)

[0 0 0 0 0]
[[0 0 0]
 [0 0 0]
 [0 0 0]]


#### `ones()`関数
すべてが1の配列作成

In [11]:
one_array1 = np.ones((2,2), dtype=int)
print(one_array1)

[[1 1]
 [1 1]]


#### `arrange()`関数
- 開始値から一定の刻み幅で生成した要素の配列作成
- 第一引数が開始値、第二が終了値、第三が刻み幅、任意で第四でstype=で型指定できるお

In [12]:
# 0~4の5要素の一次元配列
a1 = np.arange(5)
print(a1)

# ０から0.1刻みで1未満の要素を持つ配列
a2 = np.arange(0,1, 0.1)
print(a2)

# 0から1刻みで4要素配列をもつ2*2の多次元配列
a3 = np.arange(2*2).reshape(2,2)
print(a3)

[0 1 2 3 4]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
[[0 1]
 [2 3]]


#### `linspace()`関数
範囲をちょうど分割する値の配列を作成

In [13]:
a4 = np.linspace(0,100,11)
print(a4)

[  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]


#### `random.rand()`関数
乱数生成した配列を作成


In [14]:
rand_array = np.random.rand(5)
print(rand_array)

[0.14771059 0.85108473 0.61572811 0.72756809 0.9255854 ]


In [15]:
mu, sigma = 0,1
rand_normal_array = sigma *np.random.rand(10) + mu
print(rand_normal_array)



[0.46022713 0.96415683 0.56339847 0.60834033 0.02882504 0.55664406
 0.26708028 0.39177599 0.26392918 0.66377358]


### 4-1-4 csvファイルから配列作成

- `loadtxt()`でcsvを多次元配列で格納することができる。つかうんか？これ実務ではdfだからなあ

In [ ]:
score = np.loadtxt("data/simple_score.csv", delimiter=",", skiprows= 1)
# sliprowsしているのは配列に違う型要素入れられないから科目名のrowをスキップ
score

array([[  1.,  30.,  43.,  51.,  63.],
       [  2.,  39.,  21.,  49.,  56.],
       [  3.,  29.,  30.,  23.,  57.],
       [  4.,  95.,  87.,  77., 100.],
       [  5.,  70.,  71.,  78.,  67.]])

### 4-1-5 配列要素の操作

#### インデックス
リストと同じ、0から始まるし、-xでうしろから指定できる

In [23]:
a = np.array([1,3,5,7,9])
print(a)

print(a[0])
print(a[-1])

# インデックス指定で上書き
a[-1] = 0
print(a)

[1 3 5 7 9]
1
9
[1 3 5 7 0]


#### 多次元配列
- `[ [], []]`この形式やね、見たことある

In [27]:
a = np.array([[1,2,3],
              [4,5,6]])
print(a)

# 行列の要素を指定（2行目, 3列目）の6が帰る
print(a[1,2])

# 代入
a[1,2] = 0
print(a)

[[1 2 3]
 [4 5 6]]
6
[[1 2 3]
 [4 5 0]]


In [ ]:
score = np.loadtxt("data/simple_score.csv", delimiter=",", skiprows= 1)
print(score)

# 3行4列の要素
print(score[2,3])

[[  1.  30.  43.  51.  63.]
 [  2.  39.  21.  49.  56.]
 [  3.  29.  30.  23.  57.]
 [  4.  95.  87.  77. 100.]
 [  5.  70.  71.  78.  67.]]
23.0


#### スライス
array[開始位置:終了位置:ステップ]


In [ ]:
a = np.array([1,100,1000,10000])
print(a)
print(a[1:4])
print(a[2:])
print(a[:-2])

# 最初から最後まで一個飛ばし
print(a[::2])
# 反対から最初までを順繰り
print(a[::-1])

[    1   100  1000 10000]
[  100  1000 10000]
[ 1000 10000]
[  1 100]
[   1 1000]
[10000  1000   100     1]


In [41]:
# すらいすでまとめて代入
a = np.array([1,10,100,1000,10000])
print(a)

a[1:4] = 0
print(a)

[    1    10   100  1000 10000]
[    1     0     0     0 10000]


In [46]:
# 多次元配列は次元毎にスライスを指定するお
a = np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
print(a)

# 0~2までの行列をスライス
print(a[:2,:2])

# 2行2列以降をスライス
print(a[1:,1:])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]]
[[5 6]
 [8 9]]


### 要素順序の取り出し
- `for in` を使って配列要素を順番に取り出すことができりゅ

- `enumerate ()` 関数を使うと、リストと同じく、取り出しの繰り返し回数も併せて数えることができりゅ

- 多次元配列の要素の取り出しでは`ndenumerate()` 関数を用います。 

In [47]:
a1 = np.array([1,2,3,4,5,6])

for num in a1:
  print(num)

1
2
3
4
5
6


In [52]:
a2 = np.array([1,2,3,4,5,6]).reshape(2,3)

# これはインデックスごとの表示
for i, num in enumerate(a2):
  print(i,num)

# 要素ごとの座標とともに値を表示
for i,num in np.ndenumerate(a2):
  print(i, num)

0 [1 2 3]
1 [4 5 6]
(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6
