# 第４回 numpyとmatplotlib
numpyとmatplotlibの話になるよ～少し長いかも

## 4-1. numpy
- 効率的に多次元の配列を扱うことができる。
- 高速な行列演算が可能になるため、行列演算を行う科学技術計算などでよく活用される

In [1]:
import numpy as np

### 4-1-1 配列作成

In [2]:
# array () 関数で配列作成
list_to_array = np.array([1,2,3,4,5])
list_to_array

array([1, 2, 3, 4, 5])

In [3]:
# ndarrayオブジェクトとなる
tuple_to_array = np.array((1,2,3,4,5))
type(tuple_to_array)

numpy.ndarray

In [4]:
# print()で要素が空白区切り
print(list_to_array)
print(tuple_to_array)

[1 2 3 4 5]
[1 2 3 4 5]


### array()
- 第二引数で要素の型を指定できる。ただ混同はできない
- `.dtype()`で型を確認できる
- 一回指定した型も上書きできる

In [5]:
list_to_array = np.array([1,2,3,4,5], dtype = float)
list_to_array.dtype

dtype('float64')

### 4-1-2 多次元配列の作成