# 第４回 numpyとmatplotlib
numpyとmatplotlibの話になるよ～少し長いかも

## 4-1. numpy
- 効率的に多次元の配列を扱うことができる。
- 高速な行列演算が可能になるため、行列演算を行う科学技術計算などでよく活用される

In [1]:
import numpy as np

### 4-1-1 配列作成

In [2]:
# array () 関数で配列作成
list_to_array = np.array([1,2,3,4,5])
list_to_array

array([1, 2, 3, 4, 5])

In [3]:
# ndarrayオブジェクトとなる
tuple_to_array = np.array((1,2,3,4,5))
type(tuple_to_array)

numpy.ndarray

In [4]:
# print()で要素が空白区切り
print(list_to_array)
print(tuple_to_array)

[1 2 3 4 5]
[1 2 3 4 5]


### array()
- 第二引数で要素の型を指定できる。ただ混同はできない
- `.dtype()`で型を確認できる
- 一回指定した型も上書きできる

In [5]:
list_to_array = np.array([1,2,3,4,5], dtype = float)
list_to_array.dtype

dtype('float64')

### 4-1-2 多次元配列の作成
配列の中の配列

In [9]:
mul_array = np.array([[1,2,3], [4,5,6]])
print(mul_array)

# 行数と列数
print(mul_array.shape)

# 次元数
print(mul_array.ndim)

# 要素数
print(mul_array.size)

[[1 2 3]
 [4 5 6]]
(2, 3)
2
6


In [12]:
# reshape()で1次元配列を2次元配列に
a = [1,2,3,4,5,6]
a1 = np.array(a)
a2 = a1.reshape(2,3)

print(a1)
print(a2)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [14]:
# 1行1列の要素に代入(1,1)の値を1から0に変更
a2[0,0] = 0

print(a1)
print(a2)

# 多次元配列を1次元配列に戻すravel()
print(a2.ravel())

[0 2 3 4 5 6]
[[0 2 3]
 [4 5 6]]
[0 2 3 4 5 6]


### 練習
以下のリストから1次元リストを作成し、その後３＊３の多次元配列を作成してください。shapeで属性確認をしてください

In [21]:
mylist = [1,2,3,4,5,6,7,8,9]

m1 = np.array(mylist)
m = m1.reshape(3,3)
print(m)

print(m.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


### 4-1-3 様々な配列の作り方

#### `zeros()`関数
全要素が0の配列作成

In [25]:
zero_array1 = np.zeros(5, dtype=int)

# 5要素すべてが0の1次元配列
print(zero_array1)

# 3*3がすべて0の多次元配列
zero_array2 = np.zeros((3,3), dtype=int)
print(zero_array2)

[0 0 0 0 0]
[[0 0 0]
 [0 0 0]
 [0 0 0]]


#### `ones()`関数
すべてが1の配列作成

In [27]:
one_array1 = np.ones((2,2), dtype=int)
print(one_array1)

[[1 1]
 [1 1]]


#### `arrange()`関数
- 開始値から一定の刻み幅で生成した要素の配列作成
- 第一引数が開始値、第二が終了値、第三が刻み幅、任意で第四でstype=で型指定できるお

In [ ]:
# 0~4の5要素の一次元配列
a1 = np.arange(5)
print(a1)

# ０から0.1刻みで1未満の要素を持つ配列
a2 = np.arange(0,1, 0.1)
print(a2)

# 0から1刻みで4要素配列をもつ2*2の多次元配列
a3 = np.arange(2*2).reshape(2,2)
print(a3)

[0 1 2 3 4]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
[[0 1]
 [2 3]]


#### `linspace()`関数
範囲をちょうど分割する値の配列を作成

In [33]:
a4 = np.linspace(0,100,11)
print(a4)

[  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]


#### `random.rand()`関数
乱数生成した配列を作成
